name: pr_3
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - lib/assets/groups_brown.png
    - lib/assets/groups_pink.png
    - lib/assets/groups_blue.png

    - lib/assets/clock_brown.png
    - lib/assets/clock_blue.png
    - lib/assets/clock_pink.png

  uses-material-design: true
